"""Add registered_count column to events

Revision ID: 2a861a12d5fa
Revises: e01ba4bfb025
Create Date: 2026-08-19 23:37:02.390063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a861a12d5fa'
down_revision = 'e01ba4bfb025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('registered_count')

    # ### end Alembic commands ###
