"""add club to user

Revision ID: 68051426bdbe
Revises: c484ab86950c
Create Date: 2026-08-21 06:39:02.891468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68051426bdbe'
down_revision = 'c484ab86950c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('club')

    # ### end Alembic commands ###
