"""Add client_scan_id to CheckIn and CheckInConflict table

Revision ID: c484ab86950c
Revises: 3996ecb725fd
Create Date: 2026-08-20 15:19:52.262526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c484ab86950c'
down_revision = '3996ecb725fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('client_scan_id', sa.String(length=36), nullable=True),
    sa.Column('station_id', sa.String(length=100), nullable=False),
    sa.Column('device_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempted_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkin_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_conflicts_registration_id'), ['registration_id'], unique=False)

    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_scan_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_checkins_client_scan_id'), ['client_scan_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_client_scan_id'))
        batch_op.drop_column('client_scan_id')

    with op.batch_alter_table('checkin_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_conflicts_registration_id'))

    op.drop_table('checkin_conflicts')
    # ### end Alembic commands ###
